[package]
name = "rlox"
version = "0.1.0"
authors = ["TheDoctor314 <darsh.rajan95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.0.0"
